### PR TITLE
Convert "Fwrite," with stdout to 'O' packet to improve the speed

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
See the discussion here: https://github.com/adamgreen/mri/issues/26
Depends on https://github.com/adamgreen/mri/pull/29

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
see the dissusion here: https://github.com/adamgreen/mri/issues/26

**Comment by adamgreen** [comment]
I like the sentiment of this change but I don't know if I like it being implemented all the way down in IssueGdbFileWriteRequest(). The name of that function infers that  it will only issue the Fwrite request and not sometimes send a different packet type to GDB. I will leave this PR open for a bit to let me think on it for a bit. I may just end up implementing the same functionality but in a different part of the case base.

Thanks,

Adam

**Comment by xiaoxiang781216** [comment]
Another method is to add an option like MRI_THREAD_MRI.

**Comment by adamgreen** [comment]
I just pushed up commit 4ae4a29 to address this issue in a slightly different way. I tested it with ARM/mbed semi-hosting and newlib semi-hosting. Took a little bit of work to make sure that CTRL+C in GDB was still able to halt MRI if the user is spamming a lot of printf() output to the GDB console.

**Comment by xiaoxiang781216** [comment]
https://github.com/adamgreen/mri/commit/4ae4a2983a42318c473ac4998453edc6f54eee65 looks good, let's close this PR.

**Comment by adamgreen** [comment]
Cool

**Pull request closed without merging**
