### PR TITLE
Move the escape handling from memory.c to packet.c

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by adamgreen** [comment]
Why?

**Comment by xiaoxiang781216** [comment]
> Why?

1. The spec(https://sourceware.org/gdb/onlinedocs/gdb/Overview.html) doesn't couple the escape handling with the memory command, so the new command which use the binary encoding may be defined in the future.
2. It's more natural and simple to handle the escape handling in packet level instead a special command

**Comment by adamgreen** [comment]
Ok. 

Thanks for the PRs! I have merged all of them into my active development branch and I will start dogfooding them in my current project soon. I did have to fix one missed error handling case in this commit related to a truncated packet in the middle of an escape sequence. I also need to investigate a regression in the code coverage as well.

**Comment by xiaoxiang781216** [comment]
> Ok.
> 
> Thanks for the PRs! I have merged all of them into my active development branch and I will start dogfooding them in my current project soon. I did have to fix one missed error handling case in this commit related to a truncated packet in the middle of an escape sequence. I also need to investigate a regression in the code coverage as well.

Where your active development branch? We plan to improve mri in these area:

1. 64bit support
2. armv7-a/r、armv8-m、armv8-a/r
3. riscv32/64

and more patch will come in the next couple weak or month, so it's better to ensure our patch doesn't mess up with your working.

**Comment by adamgreen** [comment]
This pull request has been manually rebased and merged in to master branch. Thanks.

**Pull request closed without merging**
