### PR TITLE
fix some warming & avoid using IRQ_TYPE

### PR DESCRIPTION
**Pull request by anjiahao1**
Signed-off-by: anjiahao <anjiahao@xiaomi.com>

### CODE REVIEW

**Comment by adamgreen** [comment]
You give no reason to stop using IRQ_TYPE? In most cases the caller is expected to pass in just that type so making it uint32_t doesn't really make much sense.

**Comment by anjiahao1** [comment]
Yes, but I think IRQ_TYPE is only related to the type of external interrupt, and has nothing to do with the chip architecture

**Comment by anjiahao1** [comment]
That is to say, IRQ_TYPE must be defined before including armv7-m.h. If IRQ_TYPE is removed, we don't need to define IRQ_TYPE

**Comment by xiaoxiang781216** [comment]
Another reason: since IRQn_Type is defined in the board specific header file, it doesn't make sense to let common code depend on it. 
BTW, all hardware specific interface should be defined in https://github.com/adamgreen/mri/blob/master/core/platforms.h, but IRQn_Type isn't defined there. So from the design perspective, it's better:

1. Remove IRQn_Type from the common code
2. Define IRQn_Type in platforms.h

**Comment by adamgreen** [comment]
Thanks for the PR. I rebased and merged. I also fixed another compiler warning that fired after applying your chang while fixing rebase conflicts.

**Pull request closed without merging**
